- name: prometheus conf
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml

- name: prometheus restart
  service:
    name: prometheus
    state: restarted

- name: grafana start
  service:
    name: grafana-server
    state: started
